VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
SPLIT_KEYBOARD = yes
OLED_ENABLE = yes
ENCODER_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
RGBLIGHT_SUPPORTED = no
WS2812_DRIVER = vendor
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
WPM_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = no

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

QMK_SETTINGS = no
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = yes
